=== snd-sweden/data-storage-information-interface/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/snd-sweden/data-storage-information-interface/schema.json",
  "title": "Research data manifest",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "identifier": {
      "description": "Unique identifier for the storage manifest, http://purl.org/dc/terms/identifier",
      "type": "string"
    },
    "deleted": {
      "description": "Indicate that the manifest should be deleted.",
      "const": true
    },
    "publisher": {
      "description": "An entity responsible for making the resource available. http://purl.org/dc/terms/publisher",
      "type": "string"
    },
    "creator": {
      "description": "An entity responsible for making the resource, http://purl.org/dc/terms/creator",
      "type": "array",
      "items": {
        "description": "eppn (eduPersonPrincipalName) from SWAMID",
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "rightsHolder": {
      "description": "A organization owning or managing rights over the resource. http://purl.org/dc/terms/rightsHolder",
      "type": "string"
    },
    "dataObjects": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "identifier": {
            "description": "Unique identifiers for the data object, https://schema.org/identifier",
            "type": "string"
          },
          "name": {
            "description": "Name of the object, https://schema.org/name",
            "type": "string"
          },
          "dateCreated": {
            "description": "Date of creation, https://schema.org/dateCreated",
            "format": "date-time",
            "type": "string"
          },
          "dateModified": {
            "description": "Date when object was most recently modified, https://schema.org/dateModified",
            "format": "date-time",
            "type": "string"
          },
          "contentSize": {
            "description": "Object size in bytes, https://schema.org/contentSize",
            "type": "integer"
          },
          "contentUrl": {
            "description": "URL for the content of the object,https://schema.org/contentUrl",
            "type": "string"
          },
          "encodingFormat": {
            "description": "Media Type, https://schema.org/encodingFormat",
            "type": "string"
          },
          "immutable": {
            "description": "The object is read-only",
            "type": "boolean"
          },
          "checksum": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "type": "object",
              "properties": {
                "checksumValue": {
                  "description": "Value of the checksum, http://spdx.org/rdf/terms#checksumValue",
                  "type": "string"
                },
                "checksumAlgorithm": {
                  "description": "Algorithm used for checksum, http://spdx.org/rdf/terms#ChecksumAlgorithm",
                  "type": "string",
                  "enum": [
                    "checksum_algorithm_md5",
                    "checksum_algorithm_sha1",
                    "checksum_algorithm_sha224",
                    "checksum_algorithm_sha256",
                    "checksum_algorithm_sha384",
                    "checksum_algorithm_sha512"
                  ]
                }
              }
            }
          }
        },
        "required": [
          "identifier",
          "name",
          "checksum"
        ]
      }
    }
  },
  "required": [
    "identifier",
    "creator",
    "rightsHolder"
  ]
}

=== snd-sweden/data-storage-information-interface/example.json
{
  "publisher": "Forskningsprojektet @ Example EDU",
  "creator": ["kalkyl@example.edu"],
  "identifier": "3f2a775e-f33a-461e-a49c-b9450c7da4",
  "rightsHolder": "example.edu",
  "dataObjects": [
    {
      "identifier": "9e3bb2e3-443c-4763-97f3-a25eb9c8639d",
      "name": "projektet2021/data/readme.pdf",
      "dateCreated": "2020-09-15T07:16:46.329Z",
      "dateModified": "2021-01-15T07:20:46.978Z",
      "contentSize": 123,
      "contentUrl": "https://s3.example.com/projektet2021/data/readme.pdf",
      "encodingFormat": "application/pdf",
      "immutable": false,
      "checksum": [{
        "checksumValue": "39ae639d33cea4a287198bbcdca5e6856e6607a7c91dc4c54348031be2ad4c51",
        "checksumAlgorithm": "checksum_algorithm_sha256"
      }]
    },
    {
      "identifier": "eae959d3-a17d-42af-9510-44624213efca",
      "name": "projektet2021/data/data.csv",
      "dateCreated": "2020-09-18T07:16:46.329Z",
      "dateModified": "2020-09-18T07:16:46.329Z",
      "contentSize": 76912,
      "contentUrl": "",
      "encodingFormat": "text/csv",
      "immutable": true,
      "checksum": [{
        "checksumValue": "45ef90d63b90328915a561a1c88b2945",
        "checksumAlgorithm": "checksum_algorithm_md5"
      }]
    }
  ]
}
